# @package _global_

# Model
model:
  _target_: model.sam2.sam2base.SAM2Base
  image_encoder:
    _target_: model.sam2.utils.image_encoder.ImageEncoder
    scalp: 1
    trunk:
      _target_: model.sam2.utils.hieradet.Hiera
      embed_dim: 96
      num_heads: 1
      stages: [1, 2, 7, 2]
      global_att_blocks: [5, 7, 9]
      window_pos_embed_bkg_spatial_size: [7, 7]
    neck:
        _target_: model.sam2.utils.image_encoder.FpnNeck
        position_encoding:
          _target_: model.sam2.utils.position_encoder.PositionEmbeddingSine
          num_pos_feats: 256
          normalize: true
          scale: null
          temperature: 10000
        d_model: 256
        backbone_channel_list: [768, 384, 192, 96]
        fpn_top_down_levels: [2, 3]  # output level 0 and 1 directly use the backbone features
        fpn_interp_model: nearest
  promote_encoder:
    _target_: model.sam2.utils.promote_encoder.PromptEncoder
    embed_dim: 256
    image_embedding_size: [64, 64] # 1024 / 16
    input_image_size: [1024, 1024]
    mask_in_chans: 16
  mask_decoder:
    _target_: model.sam2.utils.mask_decoder.MaskDecoder
    num_multimask_outputs: 3
    transformer:
      _target_: model.sam2.utils.transformer.TwoWayTransformer
      depth: 2
      embedding_dim: 256
      mlp_dim: 2048
      num_heads: 8
    transformer_dim: 256
    iou_head_depth: 3
    iou_head_hidden_dim: 256
    use_high_res_features: true
    iou_prediction_use_sigmoid: true
    pred_obj_scores: true 
    pred_obj_scores_mlp: true
    use_multimask_token_for_obj_ptr: true
    dynamic_multimask_via_stability: true 
    dynamic_multimask_stability_delta: 0.5
    dynamic_multimask_stability_thresh: 0.98
  use_high_res_features_in_sam: true
  use_obj_ptrs_in_encoder: true
  proj_tpos_enc_in_obj_ptrs: true
  pred_obj_scores: true
  use_mlp_for_obj_ptr_proj: true
  no_obj_embed_spatial: true
  compile_image_encoder: False
  image_size: 1024
